<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DETAILS [
    <!ELEMENT DETAILS (EMPLOYEE+)>
    <!ELEMENT EMPLOYEE (ENO, NAME, GENDER, DOB, DOJ, DESIGNATION, BASIC, PAN,DEPARTMENT,PROJECT,WORKSFOR)>
    <!ELEMENT ENO (#PCDATA)>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT GENDER (#PCDATA)>
    <!ELEMENT DOB (#PCDATA)>
    <!ELEMENT DOJ (#PCDATA)>
    <!ELEMENT DESIGNATION (#PCDATA)>
    <!ELEMENT BASIC (#PCDATA)>
    <!ELEMENT PAN (#PCDATA)>
    <!ELEMENT DEPARTMENT (DEPT_NO, DEP_NAME, MENO)>
    <!ELEMENT DEPT_NO (#PCDATA)>
    <!ELEMENT DEP_NAME (#PCDATA)>
    <!ELEMENT MENO (#PCDATA)>
    <!ELEMENT PROJECT (PROJ_NO, PROJ_NAME, PROJ_DEPT_NO)>
    <!ELEMENT PROJ_NO (#PCDATA)>
    <!ELEMENT PROJ_NAME (#PCDATA)>
    <!ELEMENT PROJ_DEPT_NO (#PCDATA)>
    <!ELEMENT WORKSFOR (WORKSFOR_ENO, WORKSFOR_PROJ_NO, DATE_WORKED, HOURS)>
    <!ELEMENT WORKSFOR_ENO (#PCDATA)>
    <!ELEMENT WORKSFOR_PROJ_NO (#PCDATA)>
    <!ELEMENT DATE_WORKED (#PCDATA)>
    <!ELEMENT HOURS (#PCDATA)>
]>

<DETAILS>
    <EMPLOYEE>
        <ENO>1</ENO>
        <NAME>Rajesh</NAME>
        <GENDER>male</GENDER>
        <DOB>1999</DOB>
        <DOJ>2020</DOJ>
        <DESIGNATION>SDE</DESIGNATION>
        <BASIC>70000</BASIC>
        <PAN>4823724839473</PAN>
        <DEPARTMENT>
            <DEPT_NO>123</DEPT_NO>
            <DEP_NAME>CS</DEP_NAME>
            <MENO>1</MENO>
        </DEPARTMENT>
        <PROJECT>
            <PROJ_NO>1</PROJ_NO>
            <PROJ_NAME>Project1</PROJ_NAME>
            <PROJ_DEPT_NO>123</PROJ_DEPT_NO>
        </PROJECT>
        <WORKSFOR>
            <WORKSFOR_ENO>1</WORKSFOR_ENO>
            <WORKSFOR_PROJ_NO>1</WORKSFOR_PROJ_NO>
            <DATE_WORKED>2020-01-01</DATE_WORKED>
            <HOURS>8</HOURS>
        </WORKSFOR>
    </EMPLOYEE>
</DETAILS>
